name: Wizardry
version: 1.0.0-SNAPSHOT
main: dev.mintychochip.wizardry.paper.WizardryPlugin
loader: dev.mintychochip.wizardry.paper.mapgui.GlyphPluginLoader
api-version: '1.21'
author: jlo
dependencies:
  server:
    MapGUI:
      load: BEFORE
      required: true
      join-classpath: true
permissions:
  wizardry.scribe.book:
    description: Allows creating and using Scribe books.
    default: true
  wizardry.glyph.draw:
    description: Allows drawing and saving glyph maps.
    default: true
